const seedChats=[['Mariana','A gente precisa falar daquele projeto 👀','Agora','M'],['João Ferreira','Você viu a novidade do NEXO?','12:48','J'],['Família Silva','Mãe: domingo todo mundo aqui ❤️','11:32','F'],['Equipe NEXO','A arquitetura E2EE está ficando ótima.','Ontem','N']];
const chats=JSON.parse(localStorage.getItem('nexo_chats')||JSON.stringify(seedChats));
const messages=JSON.parse(localStorage.getItem('nexo_messages')||'{}');
const content=document.getElementById('content'),title=document.getElementById('viewTitle'),toast=document.getElementById('toast');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('nexo_chats',JSON.stringify(chats));localStorage.setItem('nexo_messages',JSON.stringify(messages))}
function avatar(x){return `<div class="avatar">${esc(x)}</div>`}
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2400)}
function now(){return new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function addMessage(i,text,kind='text'){const key='chat_'+i;const arr=messages[key]||(messages[key]=[]);arr.push({from:'me',text,time:now(),kind});chats[i][1]=kind==='file'?`📎 ${text}`:text;chats[i][2]=now();save();openChat(i)}
function chatsView(){title.textContent='Conversas';content.innerHTML=`<div class="panel"><div class="list">${chats.map((c,i)=>`<button class="chat" data-chat="${i}">${avatar(c[3])}<div><h3>${esc(c[0])}</h3><p>${esc(c[1])}</p></div><div class="time">${esc(c[2])}${i===0?'<div class="badge">2</div>':''}</div></button>`).join('')}</div></div>`;document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>openChat(Number(b.dataset.chat)))}
function openChat(i){const c=chats[i];title.textContent=c[0];const key='chat_'+i;const list=messages[key]||[{from:'them',text:c[1],time:c[2],kind:'text'}];content.innerHTML=`<div class="panel conversation"><div class="chatTop">${avatar(c[3])}<div><strong>${esc(c[0])}</strong><small>@${esc(c[0].toLowerCase().replace(/[^a-z0-9]+/g,''))} · conversa protegida</small></div><button class="icon" id="chatShare" title="Compartilhar">↗</button><button class="icon" id="chatBack">←</button></div><div class="bubbleList" id="bubbleList">${list.map(m=>`<div class="bubble ${m.from==='me'?'mine':''}">${m.kind==='file'?`<span>📎 ${esc(m.text)}</span>`:esc(m.text)}<small>${esc(m.time||'agora')}</small></div>`).join('')}</div><form class="composer" id="composer"><button type="button" class="icon" id="attachBtn" title="Anexar">＋</button><input id="messageInput" autocomplete="off" placeholder="Mensagem…"><button class="send" type="submit">Enviar</button></form><input type="file" id="fileInput" hidden multiple></div>`;document.getElementById('chatBack').onclick=chatsView;document.getElementById('chatShare').onclick=()=>shareText(`Conversa com ${c[0]} no NEXO`);document.getElementById('attachBtn').onclick=()=>document.getElementById('fileInput').click();document.getElementById('fileInput').onchange=e=>{[...e.target.files].forEach(f=>addMessage(i,f.name,'file'));showToast('Arquivo anexado localmente.');};document.getElementById('composer').onsubmit=e=>{e.preventDefault();const input=document.getElementById('messageInput'),text=input.value.trim();if(!text)return;addMessage(i,text);setTimeout(()=>document.getElementById('messageInput')?.focus(),0)}}
async function shareText(text){if(navigator.share){try{await navigator.share({title:'NEXO',text,url:location.href});return}catch(e){}}await navigator.clipboard?.writeText(text+' — NEXO');showToast('Texto copiado para compartilhar em outras redes.')} 
function newConversation(){const username=prompt('Digite o @usuário do contato:');if(username===null)return;const u=username.trim().replace(/^@/,'').toLowerCase();if(!/^[a-z0-9._-]{3,30}$/.test(u)){showToast('Use um @usuário com 3 a 30 caracteres.');return}const existing=chats.findIndex(c=>c[0].toLowerCase().replace(/[^a-z0-9]+/g,'')===u);if(existing>=0){openChat(existing);return}const name='@'+u;chats.unshift([name,'Nova conversa','Agora',u[0]?.toUpperCase()||'N']);save();chatsView();openChat(0);showToast(`🔐 Conversa criada com @${u}`)}
function search(){const q=prompt('Buscar por @usuário, conversa ou conteúdo:');if(!q)return;const term=q.toLowerCase();const found=chats.map((c,i)=>({c,i})).filter(x=>x.c.join(' ').toLowerCase().includes(term));if(!found.length){showToast('Nenhum resultado encontrado.');return}title.textContent='Resultados';content.innerHTML=`<div class="panel"><div class="list">${found.map(x=>`<button class="chat" data-chat="${x.i}">${avatar(x.c[3])}<div><h3>${esc(x.c[0])}</h3><p>${esc(x.c[1])}</p></div><div class="time">${esc(x.c[2])}</div></button>`).join('')}</div></div>`;document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>openChat(Number(b.dataset.chat)))}
function profile(){title.textContent='Perfil';content.innerHTML=`<div class="panel profile"><div class="profileHero">${avatar('A')}<div><h2>Ayslan</h2><p>@ayslan</p></div></div><div class="cards"><div class="card"><span>Identidade</span><b>@ayslan</b></div><div class="card"><span>Privacidade</span><b>Ativa</b></div><div class="card"><span>Recuperação</span><b>Preparada</b></div></div><button class="new" id="securityBtn">🔐 Configurações de segurança</button><button class="new secondary" id="installBtn">📲 Instalar NEXO</button><button class="new secondary" id="shareAppBtn">↗ Compartilhar NEXO</button></div>`;document.getElementById('securityBtn').onclick=()=>showToast('A base visual está pronta; E2EE real exige backend seguro e gerenciamento de chaves.');document.getElementById('installBtn').onclick=installApp;document.getElementById('shareAppBtn').onclick=()=>shareText('Conheça o NEXO — mensageiro privado por @usuário.')}
function simple(name,emoji,text){title.textContent=name;content.innerHTML=`<div class="panel"><div class="empty"><div style="font-size:42px">${emoji}</div><strong>${name}</strong><span>${text}</span></div></div>`}
function render(v){if(v==='chats')chatsView();if(v==='calls')simple('Chamadas','📞','A interface está preparada para áudio, vídeo e chamadas em grupo.');if(v==='communities')simple('Comunidades','👥','Espaço reservado para comunidades, grupos e administração.');if(v==='channels')simple('Canais','📢','Espaço reservado para canais de criadores e marcas.');if(v==='status')simple('Status','◉','Espaço reservado para fotos, vídeos e atualizações temporárias.')}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});async function installApp(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;return}showToast('No Android/Chrome, use o menu ⋮ e toque em “Instalar aplicativo”.')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)});document.getElementById('newBtn').onclick=newConversation;document.getElementById('searchBtn').onclick=search;document.getElementById('profileBtn').onclick=profile;render('chats');