import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.115.0/+esm';
const SUPABASE_URL='https://aemnbyxfqzntqztisoum.supabase.co';
const SUPABASE_KEY='sb_publishable_plnF9bvrN3oJl0NQw8ZnBw_xb7yLoRk';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const app=document.getElementById('app'),toast=document.getElementById('toast');
let me=null,profile=null,chats=[],active=null,channel=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const showToast=t=>{toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)};
const avatar=(letter='N')=>`<div class="avatar">${esc(letter).slice(0,1).toUpperCase()}</div>`;
const time=d=>new Date(d).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const uname=p=>`@${p?.username||'usuario'}`;
function authScreen(){app.innerHTML=`<div class="authShell"><div class="authCard"><div class="brand"><div class="logo">N</div><div><strong>NEXO</strong><small>privacidade por padrão</small></div></div><h1>Converse. Conecte. Desapareça.</h1><p class="authLead">Mensagens por @usuário, sincronizadas em tempo real.</p><div class="authTabs"><button id="loginTab" class="active">Entrar</button><button id="signupTab">Criar conta</button></div><form id="authForm"><input id="authUser" placeholder="@usuário" autocomplete="username" required><input id="authName" placeholder="Seu nome" autocomplete="name" style="display:none"><input id="authPass" type="password" placeholder="Senha (mínimo 8 caracteres)" autocomplete="current-password" required><button class="new" type="submit" id="authSubmit">Entrar no NEXO</button></form><small class="authHint">Seu @usuário é sua identidade no NEXO. Não exibimos telefone nem e-mail.</small></div></div>`;
let signup=false;const tab=(v)=>{signup=v;document.getElementById('loginTab').classList.toggle('active',!v);document.getElementById('signupTab').classList.toggle('active',v);document.getElementById('authName').style.display=v?'block':'none';document.getElementById('authSubmit').textContent=v?'Criar minha conta':'Entrar no NEXO'};document.getElementById('loginTab').onclick=()=>tab(false);document.getElementById('signupTab').onclick=()=>tab(true);document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const u=document.getElementById('authUser').value.trim().replace(/^@/,'').toLowerCase(),p=document.getElementById('authPass').value,n=document.getElementById('authName').value.trim();if(!/^[a-z0-9_]{3,24}$/.test(u))return showToast('Use 3–24 caracteres: letras, números ou _.');if(p.length<8)return showToast('A senha precisa ter pelo menos 8 caracteres.');try{const r=signup?await supabase.auth.signUp({email:`${u}@accounts.nexo.invalid`,password:p,options:{data:{username:u,display_name:n||u}}}):await supabase.auth.signInWithPassword({email:`${u}@accounts.nexo.invalid`,password:p});if(r.error)throw r.error;if(!r.data.session){showToast('Conta criada. A confirmação de e-mail precisa estar desativada no Auth do projeto.');return}await boot()}catch(err){showToast(err.message||'Não foi possível entrar.')}}}
async function boot(){const{data:{session}}=await supabase.auth.getSession();if(!session){authScreen();return}me=session.user;await ensureProfile();await loadChats();shell();listen();}
async function ensureProfile(){const{data:p}=await supabase.from('profiles').select('*').eq('id',me.id).maybeSingle();if(p){profile=p;return}const u=(me.user_metadata?.username||me.email?.split('@')[0]||'usuario').toLowerCase();const{data,error}=await supabase.from('profiles').insert({id:me.id,username:u,display_name:me.user_metadata?.display_name||u}).select().single();if(error)throw error;profile=data}
async function loadChats(){const{data,error}=await supabase.from('conversations').select('id,user_a,user_b,last_message_at,profiles_a:profiles!conversations_user_a_fkey(id,username,display_name),profiles_b:profiles!conversations_user_b_fkey(id,username,display_name)').or(`user_a.eq.${me.id},user_b.eq.${me.id}`).order('last_message_at',{ascending:false});if(error)throw error;chats=data||[]}
function other(c){return c.user_a===me.id?c.profiles_b:c.profiles_a}
function shell(){app.innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="logo">N</div><div><strong>NEXO</strong><small>privacidade por padrão</small></div></div><div class="me">${avatar(profile.display_name[0])}<div><b>${esc(profile.display_name)}</b><span>${uname(profile)}</span></div><button id="profileBtn" aria-label="Perfil">⋯</button></div><nav><button class="nav active" data-view="chats">💬 <span>Conversas</span><i id="chatCount">${chats.length}</i></button><button class="nav" data-view="calls">📞 <span>Chamadas</span></button><button class="nav" data-view="communities">👥 <span>Comunidades</span></button><button class="nav" data-view="channels">📢 <span>Canais</span></button><button class="nav" data-view="status">◉ <span>Status</span></button></nav><div class="secure"><span>🔐</span><div><b>Conexão segura</b><small>dados sincronizados pelo NEXO</small></div></div></aside><main class="main"><header><div><span class="eyebrow">NEXO</span><h1 id="viewTitle">Conversas</h1></div><div class="actions"><button class="icon" id="searchBtn">⌕</button><button class="new" id="newBtn">＋ Nova conversa</button></div></header><section id="content"></section></main></div>`;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)});document.getElementById('newBtn').onclick=newConversation;document.getElementById('searchBtn').onclick=search;document.getElementById('profileBtn').onclick=profile;render('chats')}
function chatsView(){document.getElementById('viewTitle').textContent='Conversas';const c=document.getElementById('content');c.innerHTML=`<div class="panel"><div class="list">${chats.length?chats.map((x,i)=>{const o=other(x);return `<button class="chat" data-chat="${x.id}">${avatar(o.display_name[0])}<div><h3>${esc(o.display_name)}</h3><p>${esc(uname(o))}</p></div><div class="time">${time(x.last_message_at)}</div></button>`}).join(''):`<div class="empty"><div style="font-size:42px">💬</div><strong>Seu NEXO começa aqui</strong><span>Crie uma conversa pelo @usuário.</span></div>`}</div></div>`;document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>openChat(b.dataset.chat))}
async function openChat(id){active=chats.find(c=>c.id===id);if(!active)return;const o=other(active);document.getElementById('viewTitle').textContent=o.display_name;const c=document.getElementById('content');c.innerHTML=`<div class="panel conversation"><div class="chatTop">${avatar(o.display_name[0])}<div><strong>${esc(o.display_name)}</strong><small>${esc(uname(o))} · online no NEXO</small></div><button class="icon" id="chatBack">←</button></div><div class="bubbleList" id="bubbleList"><div class="empty"><span>Carregando conversa…</span></div></div><form class="composer" id="composer"><button type="button" class="icon" disabled title="Anexos em breve">＋</button><input id="messageInput" autocomplete="off" placeholder="Mensagem…"><button class="send" type="submit">Enviar</button></form></div>`;document.getElementById('chatBack').onclick=()=>{active=null;chatsView()};await loadMessages();document.getElementById('composer').onsubmit=sendMessage;document.getElementById('messageInput').focus()}
async function loadMessages(){const{data,error}=await supabase.from('messages').select('*').eq('conversation_id',active.id).order('created_at',{ascending:true});if(error)return showToast(error.message);const list=document.getElementById('bubbleList');list.innerHTML=data.length?data.map(messageHtml).join(''):`<div class="empty"><strong>Nenhuma mensagem ainda</strong><span>Envie a primeira mensagem.</span></div>`;list.scrollTop=list.scrollHeight;await supabase.from('messages').update({read_at:new Date().toISOString()}).eq('conversation_id',active.id).neq('sender_id',me.id).is('read_at',null)}
function messageHtml(m){return `<div class="bubble ${m.sender_id===me.id?'mine':''}">${esc(m.body)}<small>${time(m.created_at)} ${m.sender_id===me.id?(m.read_at?'✓✓':'✓'):''}</small></div>`}
async function sendMessage(e){e.preventDefault();const input=document.getElementById('messageInput'),body=input.value.trim();if(!body||!active)return;const{error}=await supabase.from('messages').insert({conversation_id:active.id,sender_id:me.id,body});if(error)return showToast(error.message);input.value='';await supabase.from('conversations').update({last_message_at:new Date().toISOString()}).eq('id',active.id);await loadMessages()}
async function newConversation(){const username=prompt('Digite o @usuário do contato:');if(username===null)return;const u=username.trim().replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(u))return showToast('Use um @usuário válido.');if(u===profile.username)return showToast('Você não pode conversar consigo mesmo.');const{data:target,error:e}=await supabase.from('profiles').select('*').eq('username',u).maybeSingle();if(e)return showToast(e.message);if(!target)return showToast('Esse @usuário ainda não existe no NEXO.');let{data:existing}=await supabase.from('conversations').select('id,user_a,user_b,last_message_at,profiles_a:profiles!conversations_user_a_fkey(id,username,display_name),profiles_b:profiles!conversations_user_b_fkey(id,username,display_name)').or(`and(user_a.eq.${me.id},user_b.eq.${target.id}),and(user_a.eq.${target.id},user_b.eq.${me.id})`).maybeSingle();if(existing){active=existing;return openChat(existing.id)}const{data,error}=await supabase.from('conversations').insert({user_a:me.id,user_b:target.id}).select('id,user_a,user_b,last_message_at,profiles_a:profiles!conversations_user_a_fkey(id,username,display_name),profiles_b:profiles!conversations_user_b_fkey(id,username,display_name)').single();if(error)return showToast(error.message);chats.unshift(data);active=data;await openChat(data.id)}
async function search(){const q=prompt('Buscar @usuário:');if(!q)return;const u=q.trim().replace(/^@/,'').toLowerCase();const{data,error}=await supabase.from('profiles').select('id,username,display_name').ilike('username',`%${u}%`).limit(20);if(error)return showToast(error.message);const c=document.getElementById('content');document.getElementById('viewTitle').textContent='Pessoas';c.innerHTML=`<div class="panel"><div class="list">${data.filter(p=>p.id!==me.id).map(p=>`<button class="chat" data-user="${p.id}">${avatar(p.display_name[0])}<div><h3>${esc(p.display_name)}</h3><p>${esc(uname(p))}</p></div></button>`).join('')||'<div class="empty"><strong>Ninguém encontrado</strong></div>'}</div></div>`;document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>startUser(b.dataset.user))}
async function startUser(id){const{data:p}=await supabase.from('profiles').select('*').eq('id',id).single();if(!p)return;const found=chats.find(c=>{const o=other(c);return o.id===id});if(found)return openChat(found.id);const{data:c,error}=await supabase.from('conversations').insert({user_a:me.id,user_b:id}).select('id,user_a,user_b,last_message_at,profiles_a:profiles!conversations_user_a_fkey(id,username,display_name),profiles_b:profiles!conversations_user_b_fkey(id,username,display_name)').single();if(error)return showToast(error.message);chats.unshift(c);openChat(c.id)}
function profile(){document.getElementById('viewTitle').textContent='Perfil';document.getElementById('content').innerHTML=`<div class="panel profile"><div class="profileHero">${avatar(profile.display_name[0])}<div><h2>${esc(profile.display_name)}</h2><p>${esc(uname(profile))}</p></div></div><div class="cards"><div class="card"><span>Identidade</span><b>${esc(uname(profile))}</b></div><div class="card"><span>Privacidade</span><b>Ativa</b></div><div class="card"><span>Conta</span><b>Online</b></div></div><button class="new secondary" id="logoutBtn">Sair do NEXO</button></div>`;document.getElementById('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()}}
function simple(name,emoji,text){document.getElementById('viewTitle').textContent=name;document.getElementById('content').innerHTML=`<div class="panel"><div class="empty"><div style="font-size:42px">${emoji}</div><strong>${name}</strong><span>${text}</span></div></div>`}
function render(v){if(v==='chats')chatsView();if(v==='calls')simple('Chamadas','📞','Próxima etapa: áudio e vídeo em tempo real.');if(v==='communities')simple('Comunidades','👥','Próxima etapa: grupos, regras e administração.');if(v==='channels')simple('Canais','📢','Próxima etapa: canais públicos e criadores.');if(v==='status')simple('Status','◉','Próxima etapa: fotos e vídeos temporários.')}
function listen(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('nexo-messages').on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},async payload=>{if(active?.id===payload.new.conversation_id){const list=document.getElementById('bubbleList');if(list){list.insertAdjacentHTML('beforeend',messageHtml(payload.new));list.scrollTop=list.scrollHeight;if(payload.new.sender_id!==me.id)await supabase.from('messages').update({read_at:new Date().toISOString()}).eq('id',payload.new.id)}}else{await loadChats();const count=document.getElementById('chatCount');if(count)count.textContent=chats.length}}).subscribe();supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'&&!session)authScreen()})}
boot().catch(e=>{console.error(e);showToast(e.message||'Erro ao iniciar NEXO');authScreen()});