const $=s=>document.querySelector(s);const state={ollama:localStorage.ia_ollama||'http://127.0.0.1:11434',model:localStorage.ia_model||'tinyllama:latest',video:localStorage.ia_video||'http://127.0.0.1:8188'};
function sync(){ $('#ollamaUrl').value=state.ollama;$('#model').value=state.model;$('#videoUrl').value=state.video}
function setStatus(ok,text){$('#status i').style.background=ok?'#22c55e':'#f59e0b';$('#status span').textContent=text}
async function health(){try{let r=await fetch(state.ollama+'/api/tags');if(!r.ok)throw 0;setStatus(true,'Ollama conectado')}catch(e){setStatus(false,'Ollama não conectado')}}
function add(role,text){const box=$('#messages');$('.welcome')?.remove();const row=document.createElement('div');row.className='msg '+role;const b=document.createElement('div');b.className='bubble';b.textContent=text;row.appendChild(b);box.appendChild(row);box.scrollTop=box.scrollHeight;return b}
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const p=$('#prompt').value.trim();if(!p)return;$('#prompt').value='';add('user',p);const b=add('assistant','Pensando…');try{const r=await fetch(state.ollama+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:state.model,messages:[{role:'user',content:p}],stream:false})});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();b.textContent=d.message?.content||'Não recebi resposta do modelo.'}catch(err){b.textContent='Não consegui conectar ao Ollama. Abra Configurar e confira o endereço/modelo. Erro: '+err.message}});
$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#chatPanel').classList.toggle('hidden',t.dataset.tab!=='chat');$('#videoPanel').classList.toggle('hidden',t.dataset.tab!=='video')});
$('#openSettings').onclick=()=>{$('#settingsModal').classList.remove('hidden');sync()};$('#closeSettings').onclick=()=>$('#settingsModal').classList.add('hidden');
$('#saveSettings').onclick=()=>{state.ollama=$('#ollamaUrl').value.replace(/\/$/,'');state.model=$('#model').value.trim();state.video=$('#videoUrl').value.replace(/\/$/,'');localStorage.ia_ollama=state.ollama;localStorage.ia_model=state.model;localStorage.ia_video=state.video;$('#settingsModal').classList.add('hidden');health()};
$('#generateVideo').onclick=async()=>{const prompt=$('#videoPrompt').value.trim();const out=$('#videoResult');if(!prompt){out.textContent='Descreva o vídeo primeiro.';return}out.textContent='Enviando para o gerador local…';try{const r=await fetch(state.video+'/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,duration:+$('#duration').value,ratio:$('#ratio').value})});if(!r.ok)throw new Error('Gerador não respondeu');const d=await r.json();if(d.video_url){out.innerHTML='<video controls autoplay loop src="'+d.video_url+'"></video>'}else{out.textContent='O gerador recebeu o pedido, mas ainda não devolveu um vídeo. '+JSON.stringify(d)}}catch(e){out.textContent='Gerador de vídeo local não conectado. A interface está pronta para ComfyUI/Wan ou outro gerador local. '+e.message}};
sync();health();